### ISSUE TITLE
CIDR matching incorrect

### ISSUE THREAD

**Issue by Arantor** [Wedge/wedge#29]
I was implementing some IPv6 stuff in what I'm doing as a day job, looked up my own code and found this was broken and has always been broken. I figured I should do the decent thing and report the bug + fix upstream.

Subs.php contains this:
```
			// OK, so we need to figure out what's going on with these last digits.
			$cidr_ip = substr($cidr_ip, $whole_digits, 1);
			$ip = substr($ip, $whole_digits, 1);
			$mask = 16 - (2 ^ ($mask % 4));
```

Should have been:
```
			// OK, so we need to figure out what's going on with these last digits.
			$cidr_ip = hexdec(substr($cidr_ip, $whole_digits, 1));
			$ip = hexdec(substr($ip, $whole_digits, 1));
			$mask = 16 - (pow(2, ($mask % 4)));
```

**Comment by C3realGuy** [comment]
Thank you, i'm a bit worried that @Nao didn't merge it yet, but he also wasn't online on wedge.org in the last days...?!

**Comment by Nao** [comment]
Lol, can do without the extra brackets in the last line though ;)
No problem @Arantor.

@C3realGuy, I took a break because the continued lack of interest is not always great to live with. I've been evaluating all of these 'fancy' new game engines that have been out in all the years I've been out of game development, and I'm also toying around with several minor game ideas, trying to find something interesting. Nothing fantastic for now, but I need to get back into the 'game'. If by some miracle some large forum ended up converting to Wedge and providing enough donations to justify the last 5 years of work, I'm sure I could resume full-time work on the project, but honestly I don't see it happening, so don't expect any commitment from me beyond a few hours every month. I have a new mouth to feed, after all! And Wedge, as already established, doesn't pay. (I think I made approximately $10 out of it over 5 years, which wouldn't even pay for a couple months of hosting.)

I'm confident that even with the reduced workload on Wedge, it will still remain the best forum software of its kind for the next few years.
